Tradução para inglês
stack-spot/mind-dotnet-api-stack pull request #6
Opened 2022-10-18 18:53 UTC by ricardojosezup

2022-10-19 15:13 UTC, pilzzup requested changes

2022-10-19 15:13 UTC, pilzzup commented on docs/use-case-observability_en-us.md
> +Trace Plugin facilitates telemetry instrumentation of your API, through **Opentelemetry**, with exporter for **Jaeger** and **AWS X-Ray**.
Sugiro trocar facilitates por _make easy_

2022-10-19 15:13 UTC, pilzzup commented on docs/use-case-observability_en-us.md
> +Plugin Authentication provides more security for you to easily verify a user/API accesses to the restricted resources of your API.
Sugestão para a frase:

_Authentication Plugin provides more security for you to easily verify if a user/API has accesses to the restricted resources of your API._

2022-10-19 15:13 UTC, pilzzup commented on docs/use-case_en-us.md
> +Plugin Authentication provides more security for you to easily verify a user/API accesses to the restricted resources of your API.
Acompanhar use-case-observability

2022-10-19 15:13 UTC, pilzzup commented on docs/use-case_en-us.md
> +To start your development journey using the resources provided by **Mind Studio**, use this base template as an example to start developing a complete API using **C#**, **.NET** and **REST **, and ru
Acompanhar use-case-observability

2022-10-19 15:13 UTC, pilzzup commented on docs/use-case_en-us.md
> +Trace Plugin facilitates telemetry instrumentation of your API, through **Opentelemetry**, with exporter for **Jaeger** and **AWS X-Ray**.
Acompanhar use-case-observability

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +You can find the details in [Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-6.0) that describe the necessary steps for Windows, macOS and Linux.
```suggestion
If you want your application to work with Docker, you will need to add a temporary SSL certificate and mount a volume to hold that certificate.
For more details, see the [Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-6.0) that describe the necessary steps for Windows, macOS, and Linux.
```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +To build and run docker containers, run the command below in the solution root where you find the docker-compose.yml file.
```suggestion
To build and run docker containers, go to the solution root where you find the **docker-compose.yml file** and execute the command below:
```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +2. If the browser prompts you about the site's security, click "Go to localhost (not secure)". By accessing the above address, you will see the documentation for your application.
```suggestion
Your application is running, now:
1. Access https://localhost:5001/swagger to see more details.
2. If your browser prompts you about the website's security, click on **"Go to localhost (not secure)"**.  When you access this URL, you will see your application's documentation.
```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +In addition, it is easy to integrate with tools such as **Splunk** or **AWS Cloud Watch** to monitor and visualize data, ensuring the observability of your applications.
```suggestion
If you have several projects, microservices, and/or routines, with this Plugin you can maintain the quality and standard of the log information for everything, considering the different log levels.
It allows you to define Tags so you can quantify and/or classify errors, providing a view of recurring failures or preventing future problems.
It is easy to integrate with tools like **Splunk** or **AWS Cloud Watch** to monitor and visualize data, ensuring the observability of your applications.
```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +The Metrics Plugin makes it easy to measure the number of requests on a critical endpoint or monitor the size of payloads that are sent to your API.
```suggestion
The Metrics Plugin makes it easy to measure the number of requests on a critical endpoint or monitor the size of payloads that are sent to your API.

```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Trace Plugin makes it easy the telemetry instrumentation of your API, through **Opentelemetry**, with exporter for **Jaeger** and **AWS X-Ray**.
```suggestion
Trace Plugin facilitates the telemetry instrumentation of your API, through **Opentelemetry**, with an exporter for **Jaeger** and **AWS X-Ray**.

```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +The Queue Plugin simplifies the entire configuration and implementation of a decentralized environment, focused on microservices that communicate with each other, using message queues. Compared to cr
```suggestion
The Queue Plugin simplifies the entire configuration and implementation of a decentralized environment, focused on microservices that communicate with each other, using message queues. It's like creating a class, the Queue Plugin manages to abstract all the complexity for communicating with your **AWS SQS** queue.

```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +The Notification Plugin provides the features of **AWS SNS (Simple Notification Service)** so that your application can send messages to topics that will be consumed by your Subscribers, simultaneous
```suggestion
The Notification Plugin provides the **AWS SNS (Simple Notification Service)** features so your application can send messages to topics that will be consumed by your Subscribers, simultaneously sending data, information, and messages to different platforms at once.
```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Use the Secrets plugin any time you want within your application.
```suggestion
Secrets Plugin makes the management of sensitive system information with API keys, authentication tokens, or database connections easier. It was thought of using a **Secret Manager** from AWS to simplify the consumption of this information.
Use the Secrets plugin any time you want in your application.
```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Handle files using Plugin Bucket, it eliminates complexity and facilitates instrumentation with **Amazon Simple Storage Service (S3)**.
```suggestion
It handles files using the Bucket Plugin, eliminating complexity and facilitating instrumentation with **Amazon Simple Storage Service (S3)**.
```

2022-10-20 16:07 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Store data or documents trivially. Plugin Repository brings together all the capabilities of **AWS DynamoDB** in a simple and fast way.
```suggestion
Store data or documents trivially. Repository Plugin brings together all the capabilities of **AWS DynamoDB** in a simple and fast way.
```

2022-10-24 19:16 UTC, pilzzup approved these changes
Show

2022-11-04 17:10 UTC, merged